/** @format */

import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ul className="flex flex-row justify-end gap-12 pr-[100px] text-xl bg-slate-900 text-white font-semibold py-4">
					<li className="hover:text-slate-300">
						<Link href={"/"}>Home</Link>
					</li>
					<li className="hover:text-slate-300">
						<Link href={"/about"}>About</Link>
					</li>
					<li className="hover:text-slate-300">
						<Link href={"/details"}>Details</Link>
					</li>
					<li className="hover:text-slate-300">
						<Link href={"/login"}>Login</Link>
					</li>
					<li className="hover:text-slate-300">
						<Link href={"/signup"}>Signup</Link>
					</li>
					<li className="hover:text-slate-300">
						<Link href={"/study"}>Study</Link>
					</li>
				</ul>
				{children}
			</body>
		</html>
	);
}
